//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tag")]
/// Represents a tag entity in the database.
///
/// # Fields
/// - `id`: The unique identifier for the tag. This is the primary key.
/// - `name`: The name of the tag, stored as text.
/// - `created_at`: The timestamp when the tag was created. Optional.
/// - `updated_at`: The timestamp when the tag was last updated. Optional.
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ticket_tag::Entity")]
    TicketTag,
}

impl Related<super::ticket_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
