//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "ticket")]
/// Represents a ticket model in the system.
///
/// # Fields
/// - `id`: The unique identifier for the ticket.
/// - `title`: The title of the ticket.
/// - `description`: An optional description of the ticket.
/// - `status`: An optional status of the ticket.
/// - `user_id`: The optional ID of the user associated with the ticket.
/// - `created_at`: The optional timestamp when the ticket was created.
/// - `updated_at`: The optional timestamp when the ticket was last updated.
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    pub user_id: Option<i32>,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ticket_tag::Entity")]
    TicketTag,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::ticket_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TicketTag.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
